### ISSUE TITLE
Please, add Mouse middle button support.

### ISSUE THREAD

**Issue by ALEXGREENALEX** [TChatzigiannakis/InputSimulatorPlus#1]
Hello, can you add this methods:
```
Mouse.MiddleButtonDown();
Mouse.MiddleButtonUp();
Mouse.MiddleButtonClick();
Mouse.MiddleButtonDoubleClick();
```
because now impossible to emulate Mouse middle button events.

_P.S. And big thanks for the library!_

**Comment by TChatzigiannakis** [comment]
Fixed in https://github.com/TChatzigiannakis/InputSimulatorPlus/commit/3e7e875bdde4c62fc78127b4b82f5db0da512501.
