### ISSUE TITLE
Function key 7 {F7} doesn't seem to be working

### ISSUE THREAD

**Issue by quadgnim** [TChatzigiannakis/InputSimulatorPlus#13]
I've tested an app I created using InputSimulatorPlus against several PC apps that read keyboard input, and although most of the keys including function keys work fine, for some weird reason none of them acknowledge the function key F7 when it's sent as a keypress.  I don't think I'm doing anything wrong, as the other function keys seem to work fine, but not F7.  Any assistance figuring out what's wrong would be greatly appreciated.

**Comment by TChatzigiannakis** [comment]
I can't seem to reproduce this. I'm testing it right now with VS Code as a target application and all function keys, including F7, seem to work fine.

Can you include a snippet and an example of an application where other function keys work but F7 doesn't? Also, are you using the Nuget package or a specific GitHub commit?

**Comment by quadgnim** [comment]
Problem resolved. Turned out to be a conflicting driver from TrackIR that was intercepting some of the keys.

**Comment by quadgnim** [comment]
I finally discovered the issue with F7 not working (and turns out f9 and
f10).  I run an app called TrackIR which is head tracking for many games.
Well TrackIR maps f7, f9 and f10 and intercepts them, so my game where I
was trying to program them wasn't getting the key.  It's weird that when I
press and hold the key on the actual keyboard it somehow passes through,
but not using the library.  I tried to add a key hold using the timers in
the system but that wasn't working either.  Regardless, by disabling
TrackIR the Function keys all work.  Sorry for incorrectly reporting it as
a bug.

On a separate note, the Left Alt (menu) key doesn't work.  I also reported
it.  Did you have any luck determining what the issue is?

Thanks,

Larry

**Comment by TChatzigiannakis** [comment]
Glad to know you tracked down the bug! :) I'm closing this issue then.

Regarding the Left Alt key, I researched a bit a couple of weeks ago and I think I know why it doesn't work, but I want to revisit it this week to make sure I've got it right. Let's discuss it in [its own issue](https://github.com/TChatzigiannakis/InputSimulatorPlus/issues/12),

**Comment by quadgnim** [comment]
Just wanted to check in and ask if you had any update on fixing Left ALT OR
LMENU (same thing) to function correctly? It currently behaves as the right
key not the left one.

Thanks,

Larry
