### ISSUE TITLE
FileLoadException: Could not load file or assembly 'WindowsInput ...

### ISSUE THREAD

**Issue by sharwell** [TChatzigiannakis/InputSimulatorPlus#2]
I get this exception at runtime when I attempt to switch from InputSimulator to InputSimulatorPlus:

> System.IO.FileLoadException : Could not load file or assembly 'WindowsInput, Version=1.0.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

It appears that the regression was introduced by bce2abbb162a1b7203c5904b8007fc321c46eb03.

:memo: Please let me know if you need any assistance resolving this issue.

**Comment by TChatzigiannakis** [comment]
Good point. I've re-added a (new) key pair for InputSimulatorPlus in https://github.com/TChatzigiannakis/InputSimulatorPlus/commit/a533146b510be14ea676644c7c782e562067d5f6. I believe the original InputSimulator publishes both keys, so I'm following their example for convenience.

You can grab the binary by updating on NuGet.

**Comment by sharwell** [comment]
Thank you for looking so quickly! I'm hoping we hear back from Michael regarding unifying this effort but it's been a while and I'm not sure how it will go.

**Comment by sharwell** [comment]
Verified fixed 💯
