### ISSUE TITLE
Make the simulated mouse wheel speed adjustable

### ISSUE THREAD

**Issue by arition** [TChatzigiannakis/InputSimulatorPlus#3]
I find that it is often too fast for the simulated mouse wheel to scroll with a default multiplier of 120, though it is suggested by Microsoft. I suggest to make the ```MouseWheelClickSize``` field public to allow users adjust the speed of the wheel.

https://github.com/TChatzigiannakis/InputSimulatorPlus/blob/a533146b510be14ea676644c7c782e562067d5f6/WindowsInput/MouseSimulator.cs#L12

**Comment by EdonGashi** [comment]
@TChatzigiannakis can we have a response to this please?

**Comment by TChatzigiannakis** [comment]
This functionality has been exposed in https://github.com/TChatzigiannakis/InputSimulatorPlus/commit/f24d9f1dc14652281752899926121356bc5e11b4 and the corresponding NuGet package is now online.
