### ISSUE TITLE
Original Windows Input Simulator issues

### ISSUE THREAD

**Issue by fotis89** [TChatzigiannakis/InputSimulatorPlus#6]
Hello, I was wondering, what kind of issues have you experienced with the original library? What kind of applications where unsupported?

**Comment by TChatzigiannakis** [comment]
People noticed that various applications simply did not respond to input sent using the original library.

I don't have an exhaustive list of those applications. I personally stumbled upon this issue while trying to send input to the game Elite: Dangerous, another user noticed this behavior with ZSNES, and so on.

**Comment by fotis89** [comment]
I understand. it has to do with lower level emulation. Thanx
